### ISSUE TITLE
fails to install with python 3.12 based on numpy 1.24.2 pinned dependency

### ISSUE THREAD

**Issue by omdaniel** [MarkyMan4/filequery#15]
Currently filequery fails to build with python 3.12+ because of the numpy 1.24.2 pinned dependency

not sure if pyproject.toml can be used to make a flexible install that support cutting edge numpy and older

dependencies = [
  'numpy == 1.24.2; python_version < "3.12"',
  'numpy >= 1.26, < 4; python_version >= "3.12"'
]

**Comment by MarkyMan4** [comment]
It looks like I can do this right in `requirements.txt` as well. I'm thinking long-term I might switch to poetry to make dependency management a little easier

**Comment by MarkyMan4** [comment]
In 0.2.1 I'm dropping support for Python 3.7 and only supporting Python 3.8+. Numpy will be pinned to 1.26.1 so that should fix the issue you're having.

**Comment by MarkyMan4** [comment]
@omdaniel 0.2.1 is available now so you should be able to use this with Python 3.12+ now
