### ISSUE TITLE
CSV file headers

### ISSUE THREAD

**Issue by MarkyMan4** [MarkyMan4/filequery#18]
Sometimes DuckDB's read_csv_auto doesn't properly detect that a file has headers. Would be better to make filequery assume that it has headers and allow users to provide some argument to override this

**Comment by derpy4me** [comment]
I second this.
I saved a result from one of my queries into a CSV, and when I run a `select * from table`, the headers from the CSV show in the results.
I noticed that the CSV did not have anything that could be translated to an ID, and all of the columns were VARCHAR types. The type of data that was saved is correct.
I'll post more information as if I find any.

**Comment by MarkyMan4** [comment]
I think this got fixed when I upgraded the DuckDB version to 0.10.0. I haven't been able to reproduce the issue. If you're on filequery 0.2.4 and still having the issue, can you post some sample csv data that is giving you the issue?

**Comment by MarkyMan4** [comment]
Haven't been able to reproduce this since the v0.2.5 release. Closing this issue
