### ISSUE TITLE
List of advantages of using filequery vs. existing libraries

### ISSUE THREAD

**Issue by kopytjuk** [MarkyMan4/filequery#30]
Thanks for the great library and the corresponding documentation!

However, a new user which wants to query his own, say CSV files would ask: _what are the advantages of using`filequery` over other available tools, like csvkit or Apache Drill_

- https://csvkit.readthedocs.io/en/latest/scripts/csvsql.html
- https://drill.apache.org/docs/drill-in-10-minutes/

Maybe we could add a small section in the README and provide some overview over existing tools available in Python so a user can decide what is in her adavantage...

**Comment by MarkyMan4** [comment]
Hello and thank you for the feedback! It is much appreciated!

Although I haven't used csvkit or Apache Drill myself, I see where there is some overlap in functionality with filequery. I don't want to explicitly list out other projects in the README and do a comparison. I think it would be best if I make it as clear as possible what exactly filequery is, and what it is not. That way people can make their own decision on what tool to use based on what they are trying to do.

That being said, are there any gaps you noticed in the README or anything I could clarify more? Maybe it would be helpful if I added a "Use cases" section describing some tasks people might want to use filequery for?
